main/urls.py
from django.conf.urls import patterns, url, include
from main.views import MaDepartmentCreateView, MaDepartmentListView, MaDepartmentUpdateView, MaEmployeeListView, \
    MaEmployeeCreateView, MaEmployeeUpdateView, MaEmployeeFunctionListView, MaEmployeeFunctionCreateView, \
    MaEmployeeFunctionUpdateView, MaCustomerSupplierListView, MaCustomerSupplierCreateView, MaCustomerSupplierUpdateView, \
    MaEmployeeDetailView, MaCustomerSupplierDetailView, MaPersonListView, MaPersonCreateView, MaPersonUpdateView, \
    MaPersonDetailView, MaEquipmentListView, MaEquipmentCreateView, MaEquipmentDetailView, MaEquipmentUpdateView, \
    MaEquipmentTypeListView, MaEquipmentTypeCreateView, MaEquipmentTypeUpdateView, MaBankUpdateView, MaBankListView, \
    MaBankCreateView
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('',
    url(_(r'^/employee_function$'), MaEmployeeFunctionListView.as_view(), name="main_employeefunction"),
    url(_(r'^/employee_function/add$'), MaEmployeeFunctionCreateView.as_view(), name="main_employeefunction_add"),
    url(_(r'^/employee_function/(?P<pk>[0-9]+)'),include([
        url(_(r'/edit$'), MaEmployeeFunctionUpdateView.as_view(), name="main_employeefunction_edit"),
    ])),
    url(_(r'^/department$'), MaDepartmentListView.as_view(), name="main_department"),
    url(_(r'^/department/add$'), MaDepartmentCreateView.as_view(), name="main_department_add"),
    url(_(r'^/department/(?P<pk>[0-9]+)'),include([
        url(_(r'/edit$'), MaDepartmentUpdateView.as_view(), name="main_department_edit"),
    ])),
    url(_(r'^/person$'), MaPersonListView.as_view(), name="main_person"),
    url(_(r'^/person/add$'), MaPersonCreateView.as_view(), name="main_person_add"),
    url(_(r'^/person/(?P<pk>[0-9]+)'),include([
        url(_(r'^[/]$'), MaPersonDetailView.as_view(), name="main_person_detail"),
        url(_(r'/edit$'), MaPersonUpdateView.as_view(), name="main_person_edit"),
    ])),
    url(_(r'^/employee$'), MaEmployeeListView.as_view(), name="main_employee"),
    url(_(r'^/employee/add$'), MaEmployeeCreateView.as_view(), name="main_employee_add"),
    url(_(r'^/employee/(?P<pk>[0-9]+)'),include([
        url(_(r'^[/]$'), MaEmployeeDetailView.as_view(), name="main_employee_detail"),
        url(_(r'^/edit$'), MaEmployeeUpdateView.as_view(), name="main_employee_edit"),
    ])),
    url(_(r'^/customer_supplier$'), MaCustomerSupplierListView.as_view(), name="main_customer_supplier"),
    url(_(r'^/customer_supplier/add$'), MaCustomerSupplierCreateView.as_view(), name="main_customer_supplier_add"),
    url(_(r'^/customer_supplier/(?P<pk>[0-9]+)'),include([
        url(_(r'^[/]$'), MaCustomerSupplierDetailView.as_view(), name="main_customer_supplier_detail"),
        url(_(r'/edit$'), MaCustomerSupplierUpdateView.as_view(), name="main_customer_supplier_edit"),
    ])),
    url(_(r'^/equipment$'), MaEquipmentListView.as_view(), name="main_equipment"),
    url(_(r'^/equipment/add$'), MaEquipmentCreateView.as_view(), name="main_equipment_add"),
    url(_(r'^/equipment/(?P<pk>[0-9]+)'),include([
        url(_(r'^[/]$'), MaEquipmentDetailView.as_view(), name="main_equipment_detail"),
        url(_(r'/edit$'), MaEquipmentUpdateView.as_view(), name="main_equipment_edit"),
    ])),
    url(_(r'^/equipment_type$'), MaEquipmentTypeListView.as_view(), name="main_equipmenttype"),
    url(_(r'^/equipment_type/add$'), MaEquipmentTypeCreateView.as_view(), name="main_equipmenttype_add"),
    url(_(r'^/equipment_type/(?P<pk>[0-9]+)'),include([
        url(_(r'/edit$'), MaEquipmentTypeUpdateView.as_view(), name="main_equipmenttype_edit"),
    ])),
    url(_(r'^/bank$'), MaBankListView.as_view(), name="main_bank"),
    url(_(r'^/bank/add$'), MaBankCreateView.as_view(), name="main_bank_add"),
    url(_(r'^/bank/(?P<pk>[0-9]+)'),include([
        url(_(r'/edit$'), MaBankUpdateView.as_view(), name="main_bank_edit"),
    ])),
)

siscontrole/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from . import views
from django.conf import settings
from dashboard_view.views import DashboardOverviewView, DashboardProfileView
from django.utils.translation import ugettext_lazy as _


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'siscontrole.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', 'siscontrole.views.logout', name='logout'),
    url(r'^$', DashboardOverviewView.as_view(), name="dashboard_index"),
    url(r'^profile$', DashboardProfileView.as_view(), name="user_profile"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('crop_image.urls')),
    url(_(r'^main'), include('main.urls'),),
    url(_(r'^financial'), include('financial.urls'),),
)

if settings.DEBUG :
    urlpatterns += patterns('',
        (r'^uploaded_images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import permalink
from django.db.models.base import Model
from django.db.models.manager import Manager
from django.utils.translation import ugettext as _
from django_localflavor_br.br_states import STATE_CHOICES
from simple_history.models import HistoricalRecords

from crop_image.forms import CropImageModelField


class MaDepartment(Model):
    name = models.CharField(max_length=255, verbose_name=_("Department Name"))

    def __unicode__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        return 'main_department_edit', (), {'pk': self.id}

    class Meta:
        verbose_name = _("Department")
        verbose_name_plural = _("Departments")


class MaEquipmentType(Model):
    name = models.CharField(max_length=100, verbose_name=_("Equipment type name"))
    description = models.CharField(max_length=255, blank=True, null=True)

    def __unicode__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        return 'main_equipmenttype_edit', (), {'pk': self.id}

    class Meta:
        verbose_name = _("Equipment Type")
        verbose_name_plural = _("Equipment Types")


class MaEquipment(Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    equipment_type = models.ForeignKey(MaEquipmentType, verbose_name=_('Equipment Type'))
    brand = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Brand'))
    model = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Model'))
    registration = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Registration'),
                                    help_text='Número de placa, chassi etc.')
    description = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Description'))

    @permalink
    def get_absolute_url(self):
        return 'main_equipment_detail', (), {'pk': self.id}

    class Meta:
        verbose_name = _("Equipment")
        verbose_name_plural = _("Equipments")

    def __unicode__(self):
        return self.brand + ' ' + self.name


class NaturalPeopleManager(Manager):
    def get_queryset(self):
        return super(NaturalPeopleManager, self).get_queryset().filter(person_type='N')


class LegalPeopleManager(Manager):
    def get_queryset(self):
        return super(LegalPeopleManager, self).get_queryset().filter(person_type='L')


class MaPerson(Model):
    MARITAL_STATUS_CHOICES = [('S', _('Single')), ('D', _('Divorced')), ('M', _('Married')), ('W', _('Widow')), ]

    name = models.CharField(max_length=255, verbose_name=_('Name'))
    person_type = models.CharField(max_length=10, choices=(('N', _('Natural')), ('L', _('Legal'))),
                                   verbose_name=_('Person Type'), default=None)

    fantasy_name = models.CharField(max_length=255, verbose_name=_('Fantasy Name'), blank=True, null=True)
    representative = models.ForeignKey('self', null=True, verbose_name=_('Representative'))
    cnpj = models.CharField(max_length=18, blank=True, null=True, verbose_name=_('CNPJ'))

    cpf = models.CharField(max_length=14, blank=True, null=True, verbose_name=_('CPF'))
    rg = models.CharField(max_length=14, blank=True, null=True, verbose_name=_('RG'))

    # . Translators: State Registration é Inscricao estadual
    state_registration = models.CharField(max_length=11, blank=True, null=True, verbose_name=_('State Registration'))

    photo = CropImageModelField(upload_to='person/', url='/upload_photo', blank=True, null=True, verbose_name=_('Foto'))

    birth_date = models.DateField(blank=True, null=True, verbose_name=_('Birth Date'))
    gender = models.CharField(max_length='1', blank=True, null=True, verbose_name=_('Gender'),
                              choices=[('M', _('Male')), ('F', _('Female'))])
    marital_status = models.CharField(max_length='1', blank=True, null=True, choices=MARITAL_STATUS_CHOICES)

    email = models.EmailField(blank=True, null=True, verbose_name=_('Email'))
    site = models.URLField(blank=True, null=True, verbose_name=_('Site'))
    phone1 = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Phone1'))
    phone2 = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Phone2'))

    address = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Address'))
    address_number = models.CharField(max_length=15, blank=True, null=True, verbose_name=_('Address number'))
    address_complement = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Address complement'))
    city = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('City'))
    state = models.CharField(max_length=255, blank=True, null=True, choices=STATE_CHOICES, verbose_name=_('State'))
    zipcode = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Zipcode'))
    neighborhood = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Neighborhood'))

    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    history = HistoricalRecords()

    objects = Manager()
    natural_people = NaturalPeopleManager()
    legal_people = LegalPeopleManager()

    def __unicode__(self):
        return self.name

    def get_marital_status(self):
        return dict(self.MARITAL_STATUS_CHOICES).get(self.marital_status, '')

    def get_ocupation_icon(self):
        icons = ''
        if hasattr(self, 'maemployee'):
            icons += '<span class="fa fa-briefcase" title="' + _('Employee') + '"></span>'
        if hasattr(self, 'macustomersupplier'):
            icons += self.macustomersupplier.get_type_icon()
        return icons

    def get_type_icon(self):
        if self.person_type == 'N':
            return '<span class="fa fa-user" title="' + _('Natural Person') + '"></span>'
        elif self.person_type == 'L':
            return '<span class="fa fa-building" title="' + _('Legal Person') + '"></span>'
        else:
            return ''

    def get_represented(self):
        return MaPerson.legal_people.filter(representative=self).all()

    def get_document_number(self):
        if self.person_type == 'N':
            return self.cpf
        else:
            return self.cnpj

    @permalink
    def get_absolute_url(self):
        return 'main_person_detail', (), {'pk': self.id}

    class Meta:
        verbose_name = _("Person")
        verbose_name_plural = _("People")
        gender = 'F'


class MaEmployeeFunction(Model):
    name = models.CharField(max_length=100, verbose_name=_('Function Name'))
    description = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Description'))

    history = HistoricalRecords()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _("Employee Function")
        verbose_name_plural = _("Employee Functions")
        gender = 'F'

    @permalink
    def get_absolute_url(self):
        return 'main_employeefunction_edit', (), {'pk': self.id}


class MaEmployee(Model):
    function = models.ForeignKey(MaEmployeeFunction, verbose_name=_("Function"), null=True, on_delete=models.SET_NULL)
    department = models.ForeignKey(MaDepartment, verbose_name=_("Department"), null=True, on_delete=models.SET_NULL)
    person = models.OneToOneField(MaPerson)

    history = HistoricalRecords()

    def __unicode__(self):
        return self.person.name

    def get_name(self):
        return self.person.name

    @permalink
    def get_absolute_url(self):
        return 'main_employee_detail', (), {'pk': self.id}

    class Meta:
        verbose_name = _("Employee")
        verbose_name_plural = _("Employees")


class MaBank(Model):
    number = models.CharField(max_length=4, blank=True, null=True, verbose_name=_('Code'))
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    short_name = models.CharField(max_length=100, verbose_name=_('Short name'), blank=True, null=True)
    cnpj = models.CharField(max_length=18, blank=True, null=True, verbose_name=_('CNPJ'))
    site = models.URLField(blank=True, null=True, verbose_name=_('Site'))

    history = HistoricalRecords()


    def __unicode__(self):
        return (self.number + ' - ' + self.name)[:20] + '...'

    def get_code(self):
        if self.number != '':
            return self.number.zfill(3)
        return ''

    @permalink
    def get_absolute_url(self):
        return 'main_bank_edit', (), {'pk': self.id}

    class Meta:
        verbose_name = _("Bank")
        verbose_name_plural = _("Banks")


class MaCustomerSupplier(Model):
    type = models.CharField(max_length=10, choices=(('C', _('Customer')), ('S', _('Supplier')),
                                                    ('C/S', _('Customer and Supplier'))),
                            default=None,
                            verbose_name=_('Type'))
    person = models.OneToOneField(MaPerson)

    history = HistoricalRecords()

    def __unicode__(self):
        if self.person.person_type == 'N':
            return self.person.name + ' - CPF: ' + self.person.cpf
        else:
            return self.person.name + ' - CNPJ: ' + self.person.cnpj

    @permalink
    def get_absolute_url(self):
        return 'main_customer_supplier_detail', (), {'pk': self.id}

    def get_name(self):
        return self.person.name

    def get_document_number(self):
        return self.person.get_document_number()

    def get_type_icon(self):
        if self.type == 'C':
            return '<span class="fa fa-male text-success" title="' + _('Customer') + '"></span>'
        elif self.type == 'S':
            return '<span class="fa fa-truck text-danger" title="' + _('Supplier') + '"></span>'
        elif self.type == 'C/S':
            return '<span class="fa fa-male text-success" title="' + _(

main/templates/main/macustomersupplier_detail.html
{% extends "generics/dashboard_detail.html" %}
{% load i18n %}
{% load bootstrap_form %}

{% block detail %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-xs-5 col-md-4 col-lg-2">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/100%x180" src="{{ object.person.photo }}" alt="...">
                </a>
            </div>
            <div class="col-xs-7 col-md-8 col-lg-10">
                <h2>{{ object.person.name }}<br><small>{{ object.get_type_display }} {{ object.get_type_icon|safe }}</small></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6 col-lg-4">
                <address>
                    <strong>{% trans "Address" %}</strong>
                    <br>{{ object.person.address }}{% if object.person.address_number %}, {{ object.person.address_number }}{% endif %}{% if object.person.address_complement %}, {{ object.person.address_complement }}{% endif %}
                    {% if object.person.neighborhood %}<br>{{ object.person.neighborhood }}{% endif %}
                    <br>{{ object.person.city }} - {{ object.person.state }}
                    <br>
                    {% if object.person.email %}<br><span class="fa fa-envelope"></span> {{ object.person.email }}{% endif %}
                    {% if object.person.site %}<br><span class="fa fa-link"></span> {{ object.person.site }}{% endif %}
                    <br>
                    {% if object.person.phone1 %}<br><span class="fa fa-phone"></span> {{ object.person.phone1 }}{% endif %}
                    {% if object.person.phone2 %}<br><span class="fa fa-phone"></span> {{ object.person.phone2 }}{% endif %}
                </address>
            </div>
            <div class="col-xs-6 col-md-6 col-lg-8">
                {% if object.person.person_type == "N" %}
                    <strong>{% trans "Natural Person" %}</strong><br><br>
                    {% if object.person.marital_status %}<strong>{% trans 'Marital Status' %}: </strong>{{ object.person.get_marital_status_display }}<br>{% endif %}
                    {% if object.person.birth_date %}<br><strong>{% trans 'Birth Date' %}: </strong>{{ object.person.birth_date}}<br>{% endif %}
                    {% if object.person.cpf %}<br><strong>{% trans 'CPF' %}: </strong>{{ object.person.cpf}}<br>{% endif %}
                    {% if object.person.rg %}<strong>{% trans 'RG' %}: </strong>{{ object.person.rg}}<br>{% endif %}
                {%  else %}
                    <strong>{% trans "Legal Person" %}</strong><br><br>
                    {% if object.person.fantasy_name %}<strong>{% trans 'Fantasy Name' %}: </strong>{{ object.person.fantasy_name }}<br>{% endif %}
                    {% if object.person.contact_name %}<strong>{% trans 'Contact Name' %}: </strong>{{ object.person.contact_name }}<br>{% endif %}
                    {% if object.person.cnpj %}<br><strong>{% trans 'CNPJ' %}: </strong>{{ object.person.cnpj }}<br>{% endif %}

                {% endif %}
            </div>
        </div>

        {%  if object.mabankaccount_set.all|length > 0 %}
        <div class="panel panel-default">
          <div class="panel-heading"><span class="fa fa-bank"></span> {% trans "Bankaccounts" %}</div>
          <div class="panel-body">
              {% for ab in object.mabankaccount_set.all %}
                  <strong>{% trans 'Bank' %}: </strong>{{ ab.bank.name }}<br>
                  <strong>{% trans 'Agency' %}: </strong>{{ ab.agency }}<br>
                  <strong>{% trans 'Account Number' %}: </strong>{{ ab.number }}<br>
                  <br>
              {% endfor %}
          </div>
        </div>
        {%  endif %}
    </div>

</div>
{% endblock %}

main/templates/main/maemployee_detail.html
{% extends "generics/dashboard_detail.html" %}
{% load i18n %}
{% load bootstrap_form %}

{% block detail %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-xs-5 col-md-4 col-lg-2">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/100%x180" src="{{ object.person.photo }}" alt="...">
                </a>
            </div>
            <div class="col-xs-7 col-md-8 col-lg-10">
                <h2>{{ object.person.name }}<br><small>{{ object.function }}</small></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6 col-lg-4">
                <address>
                    <strong>{% trans "Address" %}</strong>
                    <br>{{ object.person.address }}{% if object.person.address_number %}, {{ object.person.address_number }}{% endif %}{% if object.person.address_complement %}, {{ object.person.address_complement }}{% endif %}
                    {% if object.person.neighborhood %}<br>{{ object.person.neighborhood }}{% endif %}
                    <br>{{ object.person.city }} - {{ object.person.state }}
                    <br>
                    {% if object.person.email %}<br><span class="fa fa-envelope"></span> {{ object.person.email }}{% endif %}
                    {% if object.person.site %}<br><span class="fa fa-link"></span> {{ object.person.site }}{% endif %}
                    <br>
                    {% if object.person.phone1 %}<br><span class="fa fa-phone"></span> {{ object.person.phone1 }}{% endif %}
                    {% if object.person.phone2 %}<br><span class="fa fa-phone"></span> {{ object.person.phone2 }}{% endif %}
                </address>
            </div>
            <div class="col-xs-6 col-md-6 col-lg-8">
                {% if object.person.marital_status %}<strong>{% trans 'Marital Status' %}: </strong>{{ object.person.get_marital_status_display }}<br>{% endif %}
                {% if object.person.birth_date %}<br><strong>{% trans 'Birth Date' %}: </strong>{{ object.person.birth_date}}<br>{% endif %}
                {% if object.person.cpf %}<br><strong>{% trans 'CPF' %}: </strong>{{ object.person.cpf}}<br>{% endif %}
                {% if object.person.rg %}<strong>{% trans 'RG' %}: </strong>{{ object.person.rg}}<br>{% endif %}
            </div>
        </div>
        {%  if object.person.mabankaccount_set.all|length > 0 %}
        <div class="panel panel-default">
          <div class="panel-heading"><span class="fa fa-bank"></span> {% trans "Bankaccounts" %}</div>
          <div class="panel-body">
              {% for ab in object.person.mabankaccount_set.all %}
                  <strong>{% trans 'Bank' %}: </strong>{{ ab.bank.name }}<br>
                  <strong>{% trans 'Agency' %}: </strong>{{ ab.agency }}<br>
                  <strong>{% trans 'Account Number' %}: </strong>{{ ab.number }}<br>
                  <br>
              {% endfor %}
          </div>
        </div>
        {%  endif %}
    </div>
</div>
{% endblock %}

main/templates/main/maemployee_form.html
{% extends "generics/dashboard_form.html" %}
{% load i18n %}
{% load bootstrap_form %}

{% block form %}
<form class="form-horizontal" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ second_form|as_bootstrap}}
    {{ form|as_bootstrap}}
    {% buttons %}
</form>
{% endblock %}

main/templates/main/maperson_detail.html
{% extends "generics/dashboard_detail.html" %}
{% load i18n %}
{% load bootstrap_form %}

{% block detail %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-xs-5 col-md-4 col-lg-2">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/100%x180" src="{{ object.photo }}" alt="...">
                </a>
            </div>
            <div class="col-xs-7 col-md-8 col-lg-10">
                <h2>{{ object.name }}<br><small>{{ object.get_type_display }} {{ object.get_type_icon|safe }} {{ object.get_ocupation_icon|safe }}</small></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-6 col-lg-4">
                <address>
                    <strong>{% trans "Address" %}</strong>
                    <br>{{ object.address }}{% if object.address_number %}, {{ object.address_number }}{% endif %}{% if object.address_complement %}, {{ object.address_complement }}{% endif %}
                    {% if object.neighborhood %}<br>{{ object.neighborhood }}{% endif %}
                    <br>{{ object.city }} - {{ object.state }}
                    <br>
                    {% if object.email %}<br><span class="fa fa-envelope"></span> {{ object.email }}{% endif %}
                    {% if object.site %}<br><span class="fa fa-link"></span> {{ object.site }}{% endif %}
                    <br>
                    {% if object.phone1 %}<br><span class="fa fa-phone"></span> {{ object.phone1 }}{% endif %}
                    {% if object.phone2 %}<br><span class="fa fa-phone"></span> {{ object.phone2 }}{% endif %}
                </address>
            </div>
            <div class="col-xs-6 col-md-6 col-lg-8">
                {% if object.person_type == "N" %}
                    <strong>{% trans "Natural Person" %}</strong><br><br>
                    {% if object.marital_status %}<strong>{% trans 'Marital Status' %}: </strong>{{ object.get_marital_status_display }}<br>{% endif %}
                    {% if object.birth_date %}<br><strong>{% trans 'Birth Date' %}: </strong>{{ object.birth_date}}<br>{% endif %}
                    {% if object.cpf %}<br><strong>{% trans 'CPF' %}: </strong>{{ object.cpf}}<br>{% endif %}
                    {% if object.rg %}<strong>{% trans 'RG' %}: </strong>{{ object.rg}}<br>{% endif %}
                {%  else %}
                    <strong>{% trans "Legal Person" %}</strong><br><br>
                    {% if object.fantasy_name %}<strong>{% trans 'Fantasy Name' %}: </strong>{{ object.fantasy_name }}<br>{% endif %}
                    {% if object.representative %}<strong>{% trans 'Representative' %}: </strong><a href="{{ object.representative.get_absolute_url }}">{{ object.representative.name }}</a><br>{% endif %}
                    {% if object.representative %}<strong>{% trans 'Representative CPF' %}: </strong><a href="{{ object.representative.get_absolute_url }}">{{ object.representative.cpf }}</a><br>{% endif %}
                    {% if object.cnpj %}<br><strong>{% trans 'CNPJ' %}: </strong>{{ object.cnpj }}<br>{% endif %}

                {% endif %}
            </div>
        </div>

        {%  if object.maemployee %}
        <div class="panel panel-default">
          <div class="panel-heading"><span class="fa fa-building"></span> {% trans "Employee Information" %}</div>
          <div class="panel-body">
              <strong>{% trans 'Department' %}: </strong>{{ object.maemployee.department }}<br>
              <strong>{% trans 'Function' %}: </strong>{{ object.maemployee.function }}<br>
          </div>
        </div>
        {%  endif %}

        {%  if object.macustomersupplier %}
        <div class="panel panel-default">
          <div class="panel-heading"><span class="fa fa-building"></span> {% trans "Customer/Supplier Information" %}</div>
          <div class="panel-body">
              {{ object.macustomersupplier.get_type_icon|safe }} {{ object.macustomersupplier.get_type_display }}<br>
          </div>
        </div>
        {%  endif %}


        {%  if object.get_represented %}
        <div class="panel panel-default">
          <div class="panel-heading"><span class="fa fa-building"></span> {% trans "Organization Information" %}</div>
          <div class="panel-body">
          {% for rep in object.get_represented %}
            {% trans 'Representative of ' %}<a href="{{rep.get_absolute_url}}">{{ rep.name }}</a><br>
          {% endfor %}
          </div>
        </div>
        {%  endif %}

        {%  if object.mabankaccount_set.all|length > 0 %}
        <div class="panel panel-default">
          <div class="panel-heading"><span class="fa fa-bank"></span> {% trans "Bankaccounts" %}</div>
          <div class="panel-body">
              {% for ab in object.mabankaccount_set.all %}
                  <strong>{% trans 'Bank' %}: </strong>{{ ab.bank.name }}<br>
                  <strong>{% trans 'Agency' %}: </strong>{{ ab.agency }}<br>
                  <strong>{% trans 'Account Number' %}: </strong>{{ ab.number }}<br>
                  <br>
              {% endfor %}
          </div>
        </div>
        {%  endif %}
    </div>

</div>
{% endblock %}